name: maze_game
description: A new Flutter project.
version: 1.0.0+1
homepage: https://github.com/pblinux/end_credits
repository: https://github.com/pblinux/end_credits

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.1.1
  stack: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.2.0

flutter:
